[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "cmflow"
description = "Building TOUGH2/Waiwera models from layers of conceptual models"
authors = [
    {name = "Angus Yeh", email = "a.yeh@auckland.ac.nz"},
]
dynamic = ["version"]
requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
readme = "README.md"
dependencies = [
    "shapely",
    "rtree",
    "PyTOUGH",
]

[project.urls]
"Homepage" = "https://github.com/cyeh015/cmflow"
"Source Code" = "https://github.com/cyeh015/cmflow"

[tool.hatch.version]
source = "vcs"

# local versions such as -0.3.3.dev0+g87d975348.d20260728 not allowed by PyPI
[tool.hatch.version.raw-options]
local_scheme = "no-local-version"


