from mulgrids import *
from t2data import *

import numpy as np

# for blocky CM
from shapely.geometry import Polygon
from shapely.geometry import LineString

# for faults CM
from cmflow.geom_3dface_utils import Face3D
from cmflow.geom_surface_utils import get_columns_intersect_polygon
from cmflow.geom_surface_utils import geo_column_polygon

from dataclasses import dataclass
import json
import time
import string
import re

START = [time.time()]
def print_wall_time(msg, loop_stop=False, total=False):
    t = time.time()
    if total:
        print(msg, ': %f seconds' % (t - START[0]))
    else:
        print(msg, ': %f seconds' % (t - START[-1]))
    if loop_stop:
        START.append(t)

def assign_chars(names, chars=string.ascii_uppercase):
    """ Assign unique characters to each name.

    Returns
    -------
    tuple(dict, str)
        A mapping from name to assigned character, and the remaining
        unused characters.
    """
    if len(names) > len(chars):
        raise Exception("Not enough characters for names")
    name_index = {n: chars[i] for i, n in enumerate(names)}
    remaining_chars = chars[len(names):]
    return name_index, remaining_chars

def natural_key(text):
    """ Convert text chunks and number chunks into a tuple of string
    and int, useful for sorting strings naturally. eg.

      data = ["F24", "F8", "F2", "F10"]
      sorted_data = sorted(data, key=natural_key)
      print(sorted_data)  # Output: ['F2', 'F8', 'F10', 'F24']
    """
    return [
        int(c) if c.isdigit() else c.lower()
        for c in re.split(r'(\d+)', text)
    ]

class LeapfrogLitho():
    """ Block Lithology Output generated by Leapfrog Energy """
    def __init__(self, litho_code, litho_name):
        self.litho_code = litho_code # Leapfrog LithoCode
        self.litho_name = litho_name # Leapfrog Lithology, exported name
        # as parsed from .litho_name
        self.faults = []
        self.rock = None # pure formation/lithology name
        self.parseLithoName()

    def __repr__(self):
        return f"LeapfrogLitho(code={self.litho_code}, name='{self.litho_name}', faults={self.faults}, rock='{self.rock}')"

    def parseLithoName(self):
        """ parse Leapfrog's Lithology names and determine the faults and pure
        lithos

        NOTE Leapfrog remove spaces from fault names, and then truncated into
             7 characters, not counting other non-ASCII characters.  Lithology
             names remain as they are in the Leapfrog project.

        Observation:
        - a string can have two parts separated by ', '
        - if there is only a single part, then is pure litho (to be confirmed!?)
        - if there are two parts, then they are faults and pure litho
        - faults are one or more faults joined by '+'
        - fault names are shorteded by removing spaces
        """
        parts = self.litho_name.split(', ')
        if len(parts) == 1:
            # As of 9 Aug 2026, I have never found any single part litho_name
            # that contains a single fault by itself.  It is always:
            #   - a pure rock lithi OR
            #   - multiple faults joined by '+'
            if '+' in parts[0]:
                self.faults = parts[0].split('+')
            else:
                self.rock = parts[0]
        elif len(parts) == 2:
            self.faults = parts[0].split('+')
            self.rock = parts[1]
        else:
            raise Exception("Unexpected Lithology name format: '%s'" % lf_litho)


class MethodProxy:
    """ A reusable proxy that maps dictionary syntax to any Python method.

    eg.
        For a class with methods get_value(key) and set_value(key, value), you
        can create a proxy like this:
            @property
            def rock(self):
                return MethodProxy(getter_method=self.get_rock,
                                   setter_method=self.set_rock)
        This enables use:
            obj.rock['AB'] = 4
            print(obj.rock['AB'])
    """
    def __init__(self, getter_method, setter_method=None,):
        self._getter = getter_method
        self._setter = setter_method

    def __getitem__(self, key):
        # Calls the passed-in getter method dynamically
        return self._getter(key)

    def __setitem__(self, key, value):
        if self._setter is None:
            raise TypeError("This property is read-only")
        self._setter(key, value)

@dataclass
class FaultRocktype:
    name: str
    faults: tuple[str, ...] = () # tuple of zero or more Leapfrog fault names
    direction: int | None = None  # 1 or 2 or None

class FaultRocktypes:
    """ obj that keeps fault info of created rocktypes (usually 2 chars in GMF)

    As more information is loaded, the registery becomes more useful.

    leapfrog name - names Leapfrog uses in the exported rocktype .csv
    display name - user can have custom full name for display
    rocktype name - characters (usually 2 in GMF) is the key used as part of rocktype naming

    .set_rocktypes() expects a rocktype code map to tuples of fault leapfrog names
    .set_directions() expects a dict mapping fault leapfrog names to int direction (or None)
    .set_display_names() expects a dict mapping fault leapfrog names to display/full names
    """
    def __init__(self, leapfrog_names):
        # initialise with a list of fault full names (as in)
        self.lf_faults = leapfrog_names

        self.display_name = {}
        self.rocktype_faults = {}
        self.fault_dir = {}

        # normally rocktype fault direction are worked out using individual
        # fault direction of faults in this rocktype, here user can overwrite
        # specific rocktype direction
        self.user_rocktype_dir = {} # user overwrite fault dir for combos

    def __getitem__(self, rocktype_name):
        """ convenience function to get a FaultRocktype object by rocktype name

        Use:
            a_faultrocktype['AB'].faults
            a_faultrocktype['AB'].directions

        """
        if rocktype_name not in self.rocktype_faults:
            raise KeyError(f"Rocktype {rocktype_name} not found in FaultRocktypes.")
        return FaultRocktype(
            name=rocktype_name,
            faults=self.rocktype_faults[rocktype_name],
            direction=self.get_rock_fault_dir(rocktype_name)
        )

    @property
    def faults(self):
        """ a list of leapfrog fault names """
        return self.lf_faults

    @property
    def rocktypes(self):
        """ a list rocktype names """
        return list(self.rocktype_faults.keys())

    @property
    def fault_direction(self):
        """ a dict of all leapfrog faults and their direction """
        return self.fault_dir

    def set_display_names(self, display_name):
        """ display_name is a dict mapping leapfrog names to display/full names
        """
        self.display_name = display_name

    def set_rocktypes(self, rock_table):
        """ rock_table is dict mapping rocktype code to tuple of leapfrog fault names

        This is usually constructed within something like .gmf_fault_rocktype_2L()
        from LeapfrogGM object.
        """
        self.rocktype_faults = rock_table

    def set_directions(self, fault_dir):
        """ fault_dir is a dict mapping leapfrog names to int direction (or None)

        Usually user should setup these manually.
        """
        for r,d in fault_dir.items():
            if r not in self.lf_faults:
                raise Exception(f"Fault {r} not found in FaultRocktypes.")
            if d not in [1,2]:
                raise Exception(f"Fault direction {d} for {r} must be 1 or 2.")
        self.fault_dir = fault_dir

    def get_rock_faults(self, rocktype_name, warn=False):
        if not self.rocktype_faults and warn:
            raise Exception("Fault table not set, see .set_rocktypes()")
        return self.rocktype_faults.get(rocktype_name, None)

    def set_rock_fault_dir(self, rocktype_name, direction):
        """ update the direction of a rocktype

        NOTE this is different from setting Leapfrog faults directions, see:
             .set_directions()
        """
        if rocktype_name not in self.rocktype_faults:
            raise Exception(f"Rocktype {rocktype_name} not found in FaultRocktypes.")
        self.user_rocktype_dir[rocktype_name] = direction

    def get_rock_fault_dir(self, rocktype_name, warn=False):
        """ return the rocktype fault direction (computed)

        Working out direction if not overwritten with self.user_rocktype_dir:
          if single fault -> fault dir
          if all faults same dir -> fault dir
          if some faults not specified -> None
          if intersected by faults with multiple direction -> None
        """
        if not self.fault_dir and warn:
            raise Exception("Fault direction not set, see .set_directions()")
        if not self.rocktype_faults and warn:
            raise Exception("Fault table not set, see .set_rocktypes()")

        # return user specified if specified
        try:
            return self.user_rocktype_dir[rocktype_name]
        except KeyError:
            pass

        # otherwise work out by using individual faults
        directions = [self.fault_dir.get(f, None) for f in self.rocktype_faults[rocktype_name]]
        if len(directions) == 1:
            return directions[0]
        elif len(set(directions)) == 1:
            return next(iter(directions))
        else:
            return None

    def export_gmf_v0(self):
        """ export a section of the GMF _dict_rocktypes.json that deals with
            faults
        """
        # GMF contents for _dict_rocktype.json
        gmf1, gmf2 = {'0':''}, {'0':''}
        for rocktype, faults in self.rocktype_faults.items():
            if len(faults) == 1:
                gmf1[rocktype[0]] = faults[0]
            elif len(faults) >= 2:
                gmf2[rocktype[1]] = "Intersection " + ", ".join(rocktype[1:])
        # sort the dict for nicer output
        gmf1 = dict(sorted(gmf1.items()))
        gmf2 = dict(sorted(gmf2.items()))
        gmf_fault = {
            "faults": {
                "rank": [1],
                "legend": gmf1,
                "direction": {f:None for f in gmf1.keys()},
                "color": {rt[:1]: None for rt, fs in self.rocktype_faults.items() if len(fs)==1},
            },
            "intersections": {
                "rank": [2],
                "legend": gmf2,
                "direction": {rt:self.get_rock_fault_dir(
                    rt, warn=False) for rt in self.rocktype_faults.keys()},
            },
        }
        return gmf_fault

    def export_gmf_convention(self, rank=[1, 2]):
        """ export a section of the GMF _dict_rocktypes.json that deals with
            faults

        NOTE This is a proposed new _dict_rocktype.json format.  I think this
             has a few advantages over the orginal (v0) format:
             + less assumptions is made about convention
             + flexibility for change in convention less likely to break toolchain
             + more information can be logically stored
        """
        gmf_fault = {
            "faults": {
                "rank": rank, # default to [1,2] ie. 2nd and 3rd character
                # WIP
                "data": {
                    "leapfrog_names": self.lf_faults,
                    "display_names": self.display_name,
                    "rocktype_faults": self.rocktype_faults,
                    "fault_dir": self.fault_dir,
                },
                # framework needs extras
                "legend": {rt: ", ".join(fs) for rt, fs in self.rocktype_faults.items()},
                "color": {rt: None for rt, fs in self.rocktype_faults.items() if len(fs)==1},
            },
        }
        return gmf_fault


class LeapfrogGM(object):
    """ Tough2 Block Lithology Output generated by Leapfrog Energy (.csv)

    .lithocodes is a list of leapfrog litho codes as ordered in the .csv
    .litholist is a list of leapfrog litho names as ordered in the .csv
    .blocklist is a dict of blocks with value of index for accessing .litholist

    """
    def __init__(self, geometry=''):
        super(LeapfrogGM, self).__init__()
        self.lithocodes = []
        self.litholist = []
        self.blocklitho = {}
        self.import_from = '' # optional, if imported from leapfrog
        self.geometry = geometry # optional, matching mulgrid geometry file

        # the following provides parsed info of the Leapfrog GM
        self.lf_lithos = [] # list of LeapfrogLitho objects (ordered as litholist)
        self.lf_block = {} # access LeapfrogLitho objects by block name
        self.rocks = [] # sorted pure lithos found
        self.faults = [] # sorted faults found

    def import_leapfrog_csv(self, filename, report=False):
        """ load geology info from Leapfrog's 'Generate rock types' feature.  The
        .csv file from Leapfrog usually starts with a table of 'LithoCode,Lithology'
        then a longer table of 'BlockName,LithoCode'.  Both of these will be
        retuened as dictionaries. """
        import csv
        f = open(filename,'r')
        allrows = csv.reader(f)
        self.lithocodes = []
        self.litholist = []
        self.blocklitho = {}
        # TODO: this file reading is ugly, need work
        code_index = {}
        read_litho_name, read_block_litho = False, False
        for row in allrows:
            if len(row) == 1: continue
            if len(row) == 3:
                if row[0] == '#' and row[1] == 'LithoCode':
                    read_litho_name = True
                    continue
            if len(row) == 2:
                if row[0] == 'BlockName' and row[1] == 'LithoCode':
                    read_litho_name = False
                    read_block_litho = True
                    continue
            if read_litho_name:
                if row[0] != '#': raise Exception
                self.lithocodes.append(row[1])
                self.litholist.append(row[2])
                code_index[int(row[1])] = len(self.litholist)-1
            if read_block_litho:
                if len(row) != 2: break
                self.blocklitho[row[0]] = code_index[int(row[1])]
        f.close()
        self.import_from = filename

        self.parse_lithology()

        if report:
            print("\n".join([
                f"Loaded from file: {self.import_from}:",
                f"{len(self.lf_lithos):>8} Leapfrog LithoCode",
                f"{len(self.lf_block):>8} Blocks allocated",
                f"{len(self.lf_faults):>8} Faults found",
                f"{len(self.lf_rocks):>8} Pure rocks (lithos) found",
                ]) + "\n")

    def parse_lithology(self):
        """ parse Leapfrog's Lithology names and determine the faults and pure
        lithos

        Returns a list of lithology and a list of faults.

        """
        self.lf_lithos = [] # list of LeapfrogLitho objects (ordered as litholist)
        self.lf_block = {} # access LeapfrogLitho objects by block name
        for code, name in zip(self.lithocodes, self.litholist):
            lf_litho = LeapfrogLitho(code, name)
            self.lf_lithos.append(lf_litho)
        for block, idx in self.blocklitho.items():
            self.lf_block[block] = self.lf_lithos[idx]

        # compile lists of faults and pure (litho) rocks
        rocks, faults = set(), set()
        for litho in self.lf_lithos:
            if litho.rock is not None:
                rocks.add(litho.rock)
            faults.update(litho.faults)
        self.lf_rocks = sorted(rocks, key=natural_key)
        self.lf_faults = sorted(faults, key=natural_key)

        for f in self.lf_faults:
            if f in self.lf_rocks:
                raise Exception(f"Fault {f} also found in pure litho list")
        for r in self.lf_rocks:
            if r in self.lf_faults:
                raise Exception(f"Pure litho {r} also found in fault list")

        return self.lf_rocks, self.lf_faults

    def gmf_litho_rocktype_1L(self, litho_codes={}, chars=None, ignore=None,
        report=False):
        """ Generates GMF style rocktype names (length of 1) based on lithologies.
        Returns a dict of mapping from GMF rocktype name to Leapfrog lithology(s).

        litho_codes is a user-defined dict with keys and values a single char.
        The order is important, will affect how the final names are sorted.
        If not specified, the names will be sorted *naturally*.  Multiple litho
        names mapping to the same code is allowed (i.e. merging rocktypes).

        chars is a string containing possible characters to use.  NOTE '0' is
        special in GMF and is reserved, it will be removed from user's chars.

        It is possible to ignore certain lithology by sepcifying names in ignore
        list.  Note that they will produce GMF rocktype '0'.  There is a default
        set of ignored litho names, if you want to include them, you will have
        to set ignore=[].

        Each block's rocktype code (length=1) can be accessed by:
            GM.lf_block[block_name].rocktype_litho
        """
        if chars is None:
            chars = string.ascii_uppercase + string.ascii_lowercase + string.digits[1:]
        else:
            chars = chars.replace('0', '')

        default_ignore = [None, 'Water', 'Unknown', 'Outside Geological Model']
        if ignore is None:
            ignore = [ig for ig in default_ignore if ig in self.lf_rocks]
        else:
            ignore = [ig for ig in ignore if ig in self.lf_rocks]

        if litho_codes:
            # some checks and remove used characters
            for l,c in litho_codes.items():
                if l in ignore and c != '0':
                    print(f"Warning: ignoring lithology {l}, "
                          f"overwrite user-defined litho_codes '{c}' -> '0'")
                if len(c) != 1:
                    raise Exception(f"Lithology code for {l} must be a single character")
                if l not in self.lf_rocks:
                    raise Exception(f"Lithology {l} not found in Leapfrog lithologies list")
                chars = chars.replace(c, '')

        for ig in ignore:
            litho_codes[ig] = '0'

        # deal with all other rocks not specified by user
        remaining_rocks = [r for r in self.lf_rocks if r not in litho_codes]
        new_litho_codes, chars = assign_chars(sorted(remaining_rocks, key=natural_key), chars)
        litho_codes.update(new_litho_codes)

        # keep as a property of LeapfrogLitho object
        for litho in self.lf_lithos:
            if litho.rock is None:
                litho.rocktype_litho = '0'
            else:
                litho.rocktype_litho = litho_codes[litho.rock]

        # create reverse index for GMF
        rocktype_litho_index = {}
        for name, rt in litho_codes.items():
            if rt not in rocktype_litho_index:
                rocktype_litho_index[rt] = name
            else:
                rocktype_litho_index[rt] += ", " + name
        # sort the dict for nicer output
        rocktype_litho_index = dict(sorted(rocktype_litho_index.items()))

        # GMF contents for _dict_rocktype.json
        gmf_litho = {
            "rank": [0],
            "legend": rocktype_litho_index,
        }

        if report:
            print()
            for code, names in rocktype_litho_index.items():
                print(f"{code} -> {names}")
            print()

        return rocktype_litho_index, gmf_litho

    def gmf_fault_rocktype_2L(self, fault_codes={}, chars=None, report=False):
        """ Generates GMF style rocktype names (length of 2) based on faults.
        Returns a dict of mapping from GMF rocktype name to tuple of faults.

        fault_code is a user-defined dict with keys and values a single char.
        The order is important, will affect how the final names are sorted.
        If not specified, the names will be sorted *naturally*.

        chars is a string containing possible characters to use.  NOTE '0' is
        special in GMF and is reserved, it will be removed from user's chars.

        GMF uses two characters:
        - 2nd char (3rd char is zero) single fault
        - 3rd char (combined with 2nd char as unique combination of faults)
        """
        if chars is None:
            chars = string.ascii_uppercase + string.ascii_lowercase + string.digits[1:]
        else:
            chars = chars.replace('0', '')

        if fault_codes:
            # some checks and remove used characters
            for f,c in fault_codes.items():
                if c == '0':
                    raise Exception(f"Fault code for {f} cannot be '0'")
                if len(c) != 1:
                    raise Exception(f"Fault code for {f} must be a single character")
                if f not in fault_codes:
                    raise Exception(f"Fault {f} not found in Leapfrog faults list")
                chars = chars.replace(c, '')
            # tolerate if user only specifies some of the faults
            remaining_lf_faults = [f for f in self.lf_faults if f not in fault_codes]
            new_fault_codes, chars = assign_chars(sorted(remaining_lf_faults, key=natural_key), chars=chars)
            fault_codes.update(new_fault_codes)
        else:
            fault_codes, chars = assign_chars(sorted(self.lf_faults, key=natural_key), chars=chars)

        fault_rank = {name: idx for idx, name in enumerate(fault_codes)}

        # sort combinations: by num of faults, then by ranking of 1st fault, then 2nd...
        def combo_id(items):
            # id (a tuple of faults) is also ordered by rank
            return tuple(sorted(items, key=lambda x: fault_rank.get(x, 0)))
        # sorting the faults to ensure unique fault sets
        combinations = list({combo_id(c.faults) for c in self.lf_lithos})
        # sort by combo length, then by rank sequentially in combo
        combinations = sorted(combinations, key=lambda x: (len(x), tuple(fault_rank[y] for y in x)))

        final_codes = {}
        for ii,fid in enumerate(combinations):
            if len(fid) == 0:
                final_codes[fid] = '00'
            elif len(fid) == 1:
                # single item ones first -> fault code + '0'
                final_codes[fid] = fault_codes[fid[0]] + '0'
            elif len(fid) == 2:
                # two items combo -> first + second
                final_codes[fid] = ''
                for fault in fid:
                    final_codes[fid] += fault_codes[fault]
            else:
                # three or more -> first fault code + nunique code
                if not chars:
                    need_more = len(combinations) - ii
                    raise Exception(f"Not enough characters for remaining fault combinations,"
                                    f" need {need_more} more.")
                code = chars[0]
                chars = chars[1:]
                final_codes[fid] = fault_codes[fid[0]] + code

        # useful properties added to LeapfrogLitho objects
        for litho in self.lf_lithos:
            fid = combo_id(litho.faults)
            litho.rocktype_fault = final_codes[fid] # eg. 'AB', 'A0', '00'
            litho.faults_sorted = fid # eg. ('Fault1', 'Fault2')

        # create reverse index for general use (key has two characters)
        rocktype_index = {}
        for faults, rocktype_name in final_codes.items():
            if rocktype_name in rocktype_index:
                raise Exception(f"Rocktype Name should be unique, {rocktype_name} repeated")
            rocktype_index[rocktype_name] = faults
        # sort the dict for nicer output
        rocktype_index = dict(sorted(rocktype_index.items()))

        # create FaultRocktypes object to return
        fault_rocktypes = FaultRocktypes(self.lf_faults)
        fault_rocktypes.set_rocktypes(rocktype_index)

        if report:
            print("\n".join([
                f"Generating GMF fault names:",
                f"{len(self.lf_lithos):>8} Leapfrog LithoCode",
                f"{len(self.lf_faults):>8} Faults found",
                f"{len(final_codes):>8} Total unique fault combinations found",
                f"{len([fid for fid in final_codes.keys() if len(fid)==1]):>8} Single-fault combinations found",
                f"{len([fid for fid in final_codes.keys() if len(fid)==2]):>8} Fault intersections found with 2 faults",
                f"{len([fid for fid in final_codes.keys() if len(fid)>=3]):>8} Fault intersections found with 3 or more faults",
                f"{max([len(fid) for fid in final_codes.keys()]):>8} Maximum number of fault intersect in one block",
                ]) + "\n")

        return fault_rocktypes

    def write(self, filename):
        with open(filename, 'w') as f:
            data = {
                "comments": [
                    "Simplified Leapfrog Geological Model",
                    "zones: a list of zone names",
                ],
                "import_from" : self.import_from,
                "geometry" : self.geometry,
                "zones": self.litholist,
                "blocks": self.blocklitho,
                # Non standard field, for LeapfrogGM only
                "import_litho_codes": self.lithocodes,
            }
            json.dump(data, f, indent=4, sort_keys=True)

    def read(self, filename):
        with open(filename, 'r') as f:
            data = json.load(f)
            self.import_from = data['import_from']
            self.geometry = data['geometry']
            self.litholist = data['zones']
            self.blocklitho = data['blocks']
            # Non standard field, for LeapfrogGM only
            self.lithocodes = data["import_litho_codes"]
            self.parse_lithology()

class CM(object):
    def populate_model(self, np_dtype):
        raise NotImplementedError

    def calc_bmstats(self, geo, np_dtype=np.single):
        stats, zones = self.populate_model(geo, np_dtype)
        bms = BMStats(geo=geo, stats=stats, zones=zones)
        return bms

class CM_Blocky(CM):
    """ A nceptual Model object is a model that represents a space by a list of
    zones (usually exists as a blocky model, each block has a *rocktype*). """
    def __init__(self, geo, grid):
        """ initialise CM model by load mulgrid geometry and t2grid objects """
        super(CM_Blocky, self).__init__()

        if isinstance(geo, str):
            self.geo = mulgrid(geo)
        elif isinstance(geo, mulgrid):
            self.geo = geo
        else:
            raise Exception("Unable to load mulgrid geometry file")

        if isinstance(grid, str):
            self._load_from_t2grid(t2data(grid).grid)
        elif isinstance(grid, t2data):
            self._load_from_t2grid(grid.grid)
        elif isinstance(grid, t2grid):
            self._load_from_t2grid(grid)
        elif isinstance(grid, LeapfrogGM):
            # if LeapfrogGM object
            self.zones = grid.litholist
            self.block = grid.blocklitho
        elif grid is None:
            # customised cm
            # !!! NOTE, .populate_model() might not work
            self.zones = []
            self.block = {}
        else:
            raise Exception("Unable to load t2grid or LeapfrogGM object")

        # caching objects, so can call populate multiple times efficiently
        self._inter_areas, self._bm_col_ccis = None, None
        self._inter_lengths, self._bm_lay_clis = None, None
        self._bm_idx = None

        self.num_zones = len(self.zones)

    def _load_from_t2grid(self, grid):
        print_wall_time('_load_from_t2grid()', loop_stop=True)
        self.zones = [r.name for r in grid.rocktypelist]
        print_wall_time('  created zones from t2grid', loop_stop=True)
        self.block = {b: grid.rocktypelist.index(grid.block[b].rocktype) for b in self.geo.block_name_list}
        print_wall_time('  created block zone dict (old method)', loop_stop=True)

    def column_intersect_area(self, geo):
        """ return an two-d array of (absolute) area of column intersections
        between the model column and CM columns.

        'bm_col_ccis' is a list the same length/order as geo.block_name_list, each
        element is a (varying length) list of cm columns that intersects bm
        column.
        """
        from rtree import index
        if self._inter_areas is not None and self._bm_col_ccis is not None:
            return self._inter_areas, self._bm_col_ccis

        bm_polys = [Polygon([n.pos for n in c.node]) for c in geo.columnlist]
        print_wall_time('    constructed all %i BM polys' % geo.num_columns, loop_stop=True)

        # CM usually has larger number of columns and is regular, so I should
        # probably do RTree on CM grid
        cm_idx = index.Index()
        cm_polys = [Polygon([n.pos for n in c.node]) for c in self.geo.columnlist]
        print_wall_time('    constructed all %i CM polys' % self.geo.num_columns, loop_stop=True)
        for i,poly in enumerate(cm_polys):
            cm_idx.insert(i, poly.bounds)
        print_wall_time('    constructed CM polys RTree', loop_stop=True)

        bm_col_ccis = [] # list of CM col indices that intersects BM columns
        areas = np.zeros((geo.num_columns, self.geo.num_columns))
        for i,bm_poly in enumerate(bm_polys):
            bm_col_ccis.append([])
            for j in cm_idx.intersection(bm_poly.bounds):
                areas[i,j] = bm_poly.intersection(cm_polys[j]).area
                if areas[i,j] > 0.0:
                    bm_col_ccis[-1].append(j)
        print_wall_time('    finished creating column intersection array', loop_stop=True)

        self._inter_areas, self._bm_col_ccis = areas, bm_col_ccis
        return areas, bm_col_ccis

    def layer_intersect_length(self, geo):
        if self._inter_lengths is not None and self._bm_lay_clis is not None:
            return self._inter_lengths, self._bm_lay_clis

        bm_lines = [LineString([(lay.bottom,0), (lay.top,0)]) for lay in geo.layerlist]
        cm_lines = [LineString([(lay.bottom,0), (lay.top,0)]) for lay in self.geo.layerlist]
        bm_lay_clis = [] # list of CM lay indices that intersects BM layers
        lengths = np.zeros((geo.num_layers, self.geo.num_layers))
        for i,bm_line in enumerate(bm_lines):
            bm_lay_clis.append([])
            for j,cm_line in enumerate(cm_lines):
                lengths[i,j] = bm_line.intersection(cm_line).length
                if lengths[i,j] > 0.0:
                    bm_lay_clis[-1].append(j)

        self._inter_lengths, self._bm_lay_clis = lengths, bm_lay_clis
        return lengths, bm_lay_clis

    def populate_model(self, geo, np_dtype=np.single):
        """ This is the core of the CM processing, fill-in the stats array.

        stats array rows are of base model blocks, and columns of the zones from
        CM.  Each cell is the portion of the block occupied by the zone.   In
        most cases, the total of each row should be 1.0.
        """
        inter_areas, bm_col_ccis = self.column_intersect_area(geo)
        print_wall_time('  column_intersect_area() finished: ',
                        loop_stop=True)
        inter_lengths, bm_lay_clis = self.layer_intersect_length(geo)
        print_wall_time('  layer_intersect_length() finished: ',
                        loop_stop=True)

        stats = np.zeros((geo.num_blocks, self.num_zones), dtype=np_dtype)
        print_wall_time('  created stats array %i x %i' % (geo.num_blocks, self.num_zones), loop_stop=True)

        def setup_block_name_index_fast(geo):
            """ based on mulgrid.setup_block_name_index()

            Note atmosphere blocks may not have proper column or layer index,
            None would be used in place.
            """
            block_ij_list = [] # (coli, layj)
            if geo.num_layers > 0:
                if geo.atmosphere_type  ==  0: # one atmosphere block
                    # bn = geo.block_name(geo.layerlist[0].name, geo.atmosphere_column_name)
                    block_ij_list.append((None, None))
                elif geo.atmosphere_type == 1: # one atmosphere block per column
                    for i,col in enumerate(geo.columnlist):
                        # bn = geo.block_name(geo.layerlist[0].name, col.name)
                        block_ij_list.append((i, None))
                for j,lay in enumerate(geo.layerlist[1:]):
                    for i,col in [(ii,col) for ii,col in enumerate(geo.columnlist) if col.surface > lay.bottom]:
                        # bn = geo.block_name(lay.name, col.name)
                        block_ij_list.append((i, j+1))
            return block_ij_list

        # cm_idx = setup_block_name_index_fast(self.geo)
        # print_wall_time('created col/lay idx for CM (new method)', loop_stop=True)
        if self._bm_idx is None:
            self._bm_idx = setup_block_name_index_fast(geo)
        print_wall_time('  created col/lay idx for BM (new method)', loop_stop=True)

        ### calculating and fillinf stats here
        for ii,(bm_ci,bm_li) in enumerate(self._bm_idx):
            if bm_ci is None or bm_li is None:
                # atmosphere blocks, skip
                continue
            bvol = geo.block_volume(geo.layerlist[bm_li], geo.columnlist[bm_ci])
            # only do check columns and layers that actually intersect current BM block
            for cm_ci in bm_col_ccis[bm_ci]:
                for cm_li in bm_lay_clis[bm_li]:
                    ivol = inter_areas[bm_ci,cm_ci] * inter_lengths[bm_li,cm_li]
                    if ivol > 0.0:
                        cb = self.geo.block_name(self.geo.layerlist[cm_li].name,
                                                 self.geo.columnlist[cm_ci].name)
                        if cb not in self.block:
                            continue
                        zi = self.block[cb]
                        # zi = self.block[self.geo.block_name_index(cb)]
                        stats[ii,zi] = stats[ii,zi] + ivol / bvol
        print_wall_time('  Finished calculating/filling stats', loop_stop=True)
        return stats, self.zones


class CM_Prism(CM):
    def __init__(self, name, polygon, ztop, zbottom):
        """ create a conceptual mode
        """
        super(CM_Prism, self).__init__()
        self.name = name
        self.polygon = polygon
        self.ztop, self.zbottom = ztop, zbottom

    def column_intersect_area(self, bm_geo):
        bm_polys = geo_column_polygon(bm_geo)
        areas = np.zeros(bm_geo.num_columns)
        for i,bm_poly in enumerate(bm_polys):
            areas[i] = self.polygon.intersection(bm_poly).area
        print_wall_time('    finished creating column intersection array', loop_stop=True)
        return areas

    def layer_intersect_length(self, bm_geo):
        bm_lines = [LineString([(lay.bottom,0), (lay.top,0)]) for lay in bm_geo.layerlist]
        cm_line = LineString([(self.ztop,0), (self.zbottom,0)])
        lengths = np.zeros(bm_geo.num_layers)
        for i,bm_line in enumerate(bm_lines):
            lengths[i] = bm_line.intersection(cm_line).length
        return lengths

    def populate_model(self, bm_geo, np_dtype=np.single):
        """ This is the core of the CM processing, fill-in the stats array.

        stats array rows are of base model blocks, and columns of the zones from
        CM.  Each cell is the portion of the block occupied by the zone.   In
        most cases, the total of each row should be 1.0.
        """
        def setup_block_name_index_fast(bm_geo):
            """ based on mulgrid.setup_block_name_index()

            Note atmosphere blocks may not have proper column or layer index,
            None would be used in place.
            """
            block_ij_list = [] # (coli, layj)
            if bm_geo.num_layers > 0:
                if bm_geo.atmosphere_type  ==  0: # one atmosphere block
                    # bn = bm_geo.block_name(bm_geo.layerlist[0].name, bm_geo.atmosphere_column_name)
                    block_ij_list.append((None, None))
                elif bm_geo.atmosphere_type == 1: # one atmosphere block per column
                    for i,col in enumerate(bm_geo.columnlist):
                        # bn = bm_geo.block_name(bm_geo.layerlist[0].name, col.name)
                        block_ij_list.append((i, None))
                for j,lay in enumerate(bm_geo.layerlist[1:]):
                    for i,col in [(ii,col) for ii,col in enumerate(bm_geo.columnlist) if col.surface > lay.bottom]:
                        # bn = bm_geo.block_name(lay.name, col.name)
                        block_ij_list.append((i, j+1))
            return block_ij_list

        inter_areas = self.column_intersect_area(bm_geo)
        print_wall_time('  column_intersect_area() finished: ', loop_stop=True)
        inter_lengths = self.layer_intersect_length(bm_geo)
        print_wall_time('  layer_intersect_length() finished: ', loop_stop=True)

        stats = np.zeros((bm_geo.num_blocks, 1), dtype=np_dtype)

        bm_idx = setup_block_name_index_fast(bm_geo)
        print_wall_time('  created col/lay idx for BM (new method)', loop_stop=True)

        ### calculating and fill-in stats here
        for ii,(bm_ci,bm_li) in enumerate(bm_idx):
            if bm_ci is None or bm_li is None:
                # atmosphere blocks, skip
                continue
            bvol = bm_geo.block_volume(bm_geo.layerlist[bm_li], bm_geo.columnlist[bm_ci])
            ivol = inter_areas[bm_ci] * inter_lengths[bm_li]
            if ivol > 0.0:
                stats[ii,0] = stats[ii,0] + ivol / bvol
        print_wall_time('  Finished calculating/filling stats', loop_stop=True)
        return stats, [self.name]


class CM_Faults(CM):
    """ Conceptual Model of faults as 3D surface (Face3D *.ts objects)

    NOTE this simplements the simple way of getting blocks crossed by faults.
    Instead of 3D Face cutting across 3D blocks/elements, I simply let 3D Face
    cuts across layer centre plane.

    if dilation is specified as a positive float, then the line will be dilated
    (.buffer) with the specified amount.  This changes the behaviour of stats,
    instead of two possible values of 0.0/1.0 for normal fault line case, this
    will return stats with intersection area ratio as other CMs.
    """
    def __init__(self, faults=None, dilation=None):
        import os.path
        super(CM_Faults, self).__init__()
        self.zones = []
        self.fault = {}
        self.dilation = None
        if isinstance(dilation, float):
            if dilation > 0.0:
                self.dilation = dilation
                print('Fault uses dilation')
        if faults is None:
            pass
        elif isinstance(faults, list):
            # a list of *.ts files to load
            for filename in faults:
                fault = Face3D()
                fault.read(filename)
                zonename = os.path.splitext(filename)[0]
                self.zones.append(zonename)
                self.fault[zonename] = fault
        elif isinstance(faults, dict):
            # dictionary of Face3D objects
            for zonename in sorted(faults.keys()):
                self.zones.append(zonename)
                self.fault = faults
        else:
            raise Exception
        self.num_zones = len(self.zones)

    def populate_model(self, geo, np_dtype=np.single):

        def column_intersect_area(dilated_line, bm_geo):
            bm_polys = geo_column_polygon(bm_geo)
            areas = np.zeros(bm_geo.num_columns)
            for i,bm_poly in enumerate(bm_polys):
                areas[i] = dilated_line.intersection(bm_poly).area
            print_wall_time('    finished creating column intersection array', loop_stop=True)
            return areas

        def column_polygons(geo):
            # CM usually has larger number of columns and is regular, so I should
            # probably do RTree on CM grid
            from rtree import index
            column_idx = index.Index()
            column_polys = [Polygon([n.pos for n in c.node]) for c in geo.columnlist]
            print_wall_time('    constructed all %i column polygons' % geo.num_columns, loop_stop=True)
            for i,poly in enumerate(column_polys):
                column_idx.insert(i, poly.bounds)
            print_wall_time('    constructed column polygons RTree', loop_stop=True)
            return column_polys, column_idx

        def setup_block_name_index_fast(geo):
            """ based on mulgrid.setup_block_name_index()

            Note atmosphere blocks may not have proper column or layer index,
            None would be used in place.
            """
            block_ij_idx = {} # { (coli, layj): block index }
            bi = 0
            if geo.num_layers > 0:
                if geo.atmosphere_type  ==  0: # one atmosphere block
                    # bn = geo.block_name(geo.layerlist[0].name, geo.atmosphere_column_name)
                    block_ij_idx[(None, 0)] = bi
                    bi += 1
                elif geo.atmosphere_type == 1: # one atmosphere block per column
                    for i,col in enumerate(geo.columnlist):
                        # bn = geo.block_name(geo.layerlist[0].name, col.name)
                        block_ij_idx[(i, 0)] = bi
                        bi += 1
                for j,lay in enumerate(geo.layerlist[1:]):
                    for i,col in [(ii,col) for ii,col in enumerate(geo.columnlist) if col.surface > lay.bottom]:
                        # bn = geo.block_name(lay.name, col.name)
                        block_ij_idx[(i, j+1)] = bi
                        bi += 1
            return block_ij_idx

        stats = np.zeros((geo.num_blocks, self.num_zones), dtype=np_dtype)
        col_polys, col_idx = column_polygons(geo)
        block_ij_idx = setup_block_name_index_fast(geo)
        print_wall_time('  setup_block_name_index_fast()', loop_stop=True)
        for jj,lay in enumerate(geo.layerlist):
            count = 0 # intersected blocks count, per layer
            z = lay.centre
            for fi,fname in enumerate(self.zones):
                fault = self.fault[fname]
                fault.set_cutting_plane((0.0,0.0,z), (0.0,0.0,1.0))
                pts = fault.search_line()
                if len(pts) < 2:
                    # not enough points to construct LineString, layer not
                    # cutting through the fault Face
                    print("    skipping layer %i '%s' with fault '%s'" % (jj, lay.name, fname))
                    continue
                line = LineString([tuple(pt[:2]) for pt in pts])
                if self.dilation is not None:
                    line = line.buffer(self.dilation)
                    for ii in col_idx.intersection(line.bounds):
                        iarea = line.intersection(col_polys[ii]).area
                        if iarea > 0.0:
                            if (ii,jj) in block_ij_idx:
                                bi = block_ij_idx[(ii,jj)]
                                c = geo.column_name(geo.block_name_list[bi])
                                carea = geo.column[c].area
                                stats[bi,fi] = stats[bi,fi] + iarea / carea
                                count += 1
                else:
                    for ii in col_idx.intersection(line.bounds):
                        if line.intersection(col_polys[ii]).length > 0.0:
                            if (ii,jj) in block_ij_idx:
                                bi = block_ij_idx[(ii,jj)]
                                stats[bi,fi] = 1.0
                                count += 1
                                # print 'found ', geo.block_name_list[bi]
            print_wall_time('  finished layer %i, found %i blocks' % (jj, count), loop_stop=True)
        return stats, self.zones


class BMStatsError(Exception):
    pass

class BMStats(object):
    """ Base Model Stats, mainly numpy arrays with rows corresponding to mulgrid
    blocks, and columns corresponding to zones.  Each is a value, usually
    between 0.0 and 1.0.  Often 1.0 is indicating that particular block is fully
    within the zone.

    .stats numpy array (n,m), n = num of model blocks, m = num of zones
    .zones list of zone names (str)
    .zonestats dict of stats column by zone names
    .cellstats dict of stats row by block name
    """
    def __init__(self, filename=None, geo=None, stats=None, zones=None,
                 np_dtype=np.single):
        """
        Usage:
            # will load: .json .npy and geometry file
            bms = BMStats('abc.json')

            # geo already loaded, "geometry" in abc.json no longer matter
            bms = BMStats('abc.json', geo=geo)

            # new empty BMStats, using pre-loaded geo
            geo = mulgrid('xyz.dat')
            bms = BMStats(geo=geo)
        """
        # load from file
        if filename is not None:
            if geo is None:
                self.load(filename)
            else:
                # if geo is specified (pre-loaded)
                self.geo = geo
                self.load(filename, load_geo=False)
            return
        # new/empty
        self.geo, self.stats, self.zones = geo, stats, zones
        if geo is None:
            raise BMStatsError("New/empty BMStats requires a valid mulgrid geometry passed in as 'geo'")
        n = geo.num_blocks
        if zones is None:
            self.zones = []
        if stats is None:
            self.stats = np.zeros((n, len(self.zones)), dtype=np_dtype) # 'empty' array, ready to concatenate etc
        self._reindex()

    def __repr__(self):
        r = []
        sh = self.stats.shape
        r.append('BMStats with {} zones and {} cells'.format(sh[1], sh[0]))
        if self.filename:
            r.append(", file '{}'".format(self.filename))
        return ''.join(r)

    def _reindex(self):
        if self.stats.shape != (self.geo.num_blocks, len(self.zones)):
            raise BMStatsError('.stats shape {} mismatches (.geo.num_blocks, len(.zones)) {}'.format(self.stats.shape, (self.geo.num_blocks, len(self.zones))))
        self.zonestats = {z:self.stats[:,i] for i,z in enumerate(self.zones)}
        self.cellstats = {b:self.stats[i,:] for i,b in enumerate(self.geo.block_name_list)}

    def save(self, filename):
        import os.path
        root, ext = os.path.splitext(filename)
        npy_filename = root + '.npy'
        np.save(npy_filename, self.stats)
        # the .npy file will be expected in the same directory, so strip dir
        npy_filename = os.path.split(npy_filename)[1]
        data = {
            "comments": [
                "BM geometry: %s" % self.geo.filename,
            ],
            "stats": npy_filename,
            "zones": self.zones,
            "geometry": None,
            }
        if self.geo is not None:
            data["geometry"] = self.geo.filename
        with open(filename, 'w') as f:
            json.dump(data, f, indent=True, sort_keys=True)
        self.filename = filename

    def load(self, filename, load_geo=True):
        import os.path
        with open(filename, 'r') as f:
            data = json.load(f)
        if load_geo:
            self.geo = mulgrid(data['geometry'])
        self.zones = data['zones']
        # .npy file expected relative to the json file
        npy_filename = os.path.join(os.path.split(filename)[0], data["stats"])
        self.stats = np.load(npy_filename)
        n = self.stats.shape[0]
        if n != self.geo.num_blocks:
            msg1 = 'Loaded BMStats has different number of blocks to geometry file.'
            msg2 = 'BMStats (%i) != Geometry (%i)' % (n, self.geo.num_blocks)
            raise BMStatsError('\n'.join([msg1, msg2]))
        self.filename = filename
        self._reindex()

    def add_zone(self, zone, stats):
        """ append a single zone, with stats an array (n,1) n is number of
        blocks
        """
        if zone in self.zones:
            raise BMStatsError('zone {} already in BMStats.zones'.format(zone))
        self.zones.append(zone)
        stats = np.reshape(np.array(stats), (self.stats.shape[0], 1))
        self.stats = np.concatenate((self.stats, stats), axis=1)
        self._reindex()

    def add_stats(self, stats, zones):
        for i,zz in enumerate(zones):
            ss = stats[:,i:i+1]
            if zz in self.zones:
                ii = self.zones.index(zz)
                self.stats[:,ii] = self.stats[:,ii] + ss[:,0]
            else:
                self.stats = np.concatenate((self.stats, ss), axis=1)
                self.zones.append(zz)
        self._reindex()

    def add_cm(self, cm):
        stats, zones = cm.populate_model(self.geo)
        self.add_stats(stats, zones)

    def blocks_in_zone(self, zone, indices=False):
        """ Returns a tuple of (blocks, ratios).  blocks is a list of all blocks
        intersect the zone and ratios are portions of each respective block's
        intersection with the zone.  If indices is set to True, block indices
        are returned instead of block names.

        It is assumed self.geo is a laoded mulgrid object.

        Ratios calculation assumes the whole zone is fully within the BM.
        """
        nis = np.nonzero(self.zonestats[zone])[0]
        nvs, nbs = [], []
        for i in nis:
            b_name = self.geo.block_name_list[i]
            b_lay = self.geo.layer[self.geo.layer_name(b_name)]
            b_col = self.geo.column[self.geo.column_name(b_name)]
            nvs.append(self.geo.block_volume(b_lay, b_col) * self.zonestats[zone][i])
            nbs.append(b_name)
        nrs = [v/sum(nvs) for v in nvs]
        if indices:
            return nis, nrs
        else:
            return nbs, nrs



if __name__ == '__main__':
    # test_cm_blocky_full()
    # test_cm_fault_full()
    test_zonestats_small()
    pass