name: Unit Tests

on:
  push:
    branches:
    - '*'
    - '!master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-c1v5
        sudo apt-get install -y libspatialindex-dev
        python -m pip install --upgrade pip
        pip install setuptools
        pip install numpy
        pip install matplotlib
        pip install shapely
        pip install rtree
        pip install descartes
        mkdir pytough
        cd pytough
        git clone https://github.com/acroucher/PyTOUGH.git .
        pip install .
        cd ..
    - name: Unit tests
      run: |
        python -c "import sys; print(sys.version)"
        python -m unittest discover -v
